services:
  srp-db:
    container_name: srp-db
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: srp-postgres
      PGDATA: /data/postgres
    ports:
      - 5432:5432
    volumes:
      - ./data/pg:/data/postgres
